=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Container Application Design
* kennen die Konzepte des Container Application Designs (Container Pattern), um...
** Software-Komponenten moderner Architekturen in Container modularisieren zu können. Zum Beispiel:
*** Ambassador/Adapter/Sidekick
*** Scatter & Gather
*** Work Queue
** technische von fachlichen Aufgaben durch getrennte Container zu realisieren
** bei Verwendung eines Container-Managers übliche Aufgaben zu realisieren, insbesondere:
*** Konfiguration und Initialisierung der Applikation
*** Adaptierte Skalierung über Custom Metrics
*** Managed Container durch Operator bzw. Controller

[[LZ-4-2]]
==== LZ 4-2: Resilience
* verstehen, dass bei einer verteilten Anwendung die Kommunikation von außen und zwischen den Services fehlertolerant realisiert werden muss
** verstehen durch welche Pattern die notwendige Fehlertoleranz auf der Kommunikationsebene sichergestellt werden kann
** verstehen wie man gängige Service-Mesh-Konzepte verwenden kann, um Resilience Patterns vom fachlichen Code zu trennen und warum ein Service Mesh für moderne Webanwendungen sinnvoll ist. Besprochene Pattern sind u. a.:
*** Circuit Breaker
*** Conditional Rate Limits
*** Traffic Shifting

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Container Application Design
* know the concepts of container application design (container pattern) in order...
** to be able to modularize software components of modern architectures into containers. For example:
*** Ambassador/Adapter/Sidekick
*** Scatter & Gather
*** Work Queue
** to realize technical and business tasks through separate containers
** to realize common tasks when using a container manager, in particular:
*** Configuration and initialization of the application
*** adapted scaling via custom metrics
*** Managed container by Operator or Controller

[[LG-4-2]]
==== LG 4-2: Resilience
* Understand that with a distributed application, communication from the outside and between services must be implemented in a fault-tolerant manner
** Understand which patterns can be used to ensure the necessary fault tolerance at communication level
** understand how to use common service mesh concepts to separate resilience patterns from business code and why a service mesh makes sense for modern web applications. Patterns discussed include:
*** Circuit Breaker
*** Conditional Rate Limits
*** Traffic Shifting
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
// end::REMARK[]
