= iSAQB Advanced Level curriculum for CLOUDINFRA - Infrastructure, Container and Cloud Native

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status 
image:https://github.com/isaqb-org/curriculum-cloudinfra/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-cloudinfra/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-cloudinfra.svg["Contributors",link="https://github.com/isaqb-org/curriculum-cloudinfra/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-cloudinfra.svg["Issues",link="https://github.com/isaqb-org/curriculum-cloudinfra/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-cloudinfra.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-cloudinfra/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains a template for iSAQB Advanced Level *curricula* in AsciiDoc.
This repository contains the iSAQB Advanced Level curriculum for CLOUDINFRA - Infrastructure, Container and Cloud Native in AsciiDoc.

toc::[]

== How to contribute or participate
Create an issue, a merge- or pull-request

== How to work with the curriculum

. Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-cloudinfra.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-cloudinfra.git --recursive
----
--
. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK) via `./gradle-tools/gradlew buildDocs`.
. Once the "BUILD SUCCESSFUL" is show, you can review the build result under `./build/index.html`


== Additional translations/languages
include::docs-ext/EXTERNAL_DOCUMENTS_README.adoc[]

== Maintainers

This repository is currently maintained by Benjamin Wolf.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
