=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Projekte in Cloud-Umgebungen umsetzen

Softwarearchitekt:innen wissen, dass es bei der Arbeit in Cloud-Umgebungen neue Anforderungen an den Softwareentwicklungsprozess gibt.

Sie kennen verschiedene Vorgehensweisen, um Projekte in Cloud-Umgebungen durchzuführen. Zum Beispiel:

* Organisatorische Good Practices
* Development- und CI/CD-Umgebungen

Sie kennen Möglichkeiten, um in einer Cloud-Umgebung Deployments und ein Application Lifecycle Management zu realisieren, insbesondere:

* Versionierung von Containern und Deployment-Spezifikationen etc.
* Etablierte Formen der Bereitstellung von Anwendungen, wie z. B.:
** Rolling Deployment
** Canary Deployment
** Blue/Green Deployment

Sie kennen Komponenten und Vorgehensmodelle, um einen schnellen Test- und Deployment-Prozess zu realisieren. Insbesondere Konzepte zum Dev/Test/Prod Cluster wie:

* Verantwortlichkeiten und Zugriffskontrolle
* Good Practices zur Komponentengruppierung


// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Implementing Projects in Cloud Environments

Software architects are aware that working in cloud environments brings new requirements to the software development process.

They are familiar with different approaches to implementing projects in cloud environments, such as:

* Organizational good practices
* Development and CI/CD environments

They understand the possibilities of implementing deployments and application lifecycle management in a cloud environment, particularly:

* Versioning of containers and deployment specifications, etc.
* Established forms of application deployment, such as:
** Rolling deployment
** Canary deployment
** Blue/green deployment

They are familiar with components and models for achieving a fast testing and deployment process, particularly concepts related to dev/test/prod clusters, such as:

* Responsibilities and access control
* Good practices for component grouping

// end::EN[]
