=== {learning-goals}

// tag::DE[]
[[LZ-3-1]]
==== LZ 3-1: Nutzen und Ziele des Cloud Native Konzepts verstehen

Softwarearchitekt:innen verstehen den Nutzen und die Ziele des Cloud Native Konzepts. Sie kennen die Vorteile des Konzepts insbesondere durch:

* Einheitliche Schnittstellen zur Administration und Konfiguration
* Ressourcen-Abstraktion
* Lieferartefakte
* Isolation der Applikation vom Hostsystem

Literatur: <<davis>>

[[LZ-3-2]]
==== LZ 3-2: Grundlegende Container Konzepte verstehen

Softwarearchitekt:innen verstehen die technischen Grundlagen und den Mehrwert von Containern und kennen den Unterschied zwischen konventionellem Deployment und dem mit Containern.

Sie verstehen, wie die Verwendung von Containern zu einer besseren Entkopplung von Verantwortlichkeiten und damit zu einer effektiveren Organisation führt.

Softwarearchitekt:innen verstehen Linux-Kernel-Isolationsmechanismen, die bei Containern Anwendung finden (Container Security), u. a.:

* Namespaces und cgroups
* Capabilities

Sie kennen außerdem die Auswirkungen, Nutzungszenarien und Gefahren privilegierter Container.

[[LZ-3-3]]
==== LZ 3-3: Abstraktionskonzepte von Container-Managern verstehen

Softwarearchitekt:innen verstehen die Abstraktionskonzepte aktueller Container-Manager und kennen bewährte Muster und Praktiken, wie die Erfüllung von Qualitätsanforderungen auf sie übertragen werden kann. Zum Beispiel:

* Finite Workloads wie (Cron-) Jobs
* Health Check und Self Healing
* Skalierung und Load Balancing
* Placement

Literatur: <<bruns>>, <<bilgin_huss>>

Softwarearchitekt:innen kennen die Prinzipien eines Overlay-Networks (VLAN) für Container und Container-Manager und verstehen, wie verschiedene Services oder Systeme isoliert werden. Sie kennen Anforderungszenarien wie z. B. die Realisierung einer verteilten Firewall zur Isolation von:

* Mehreren Mandanten
* Testsystemen im Rahmen von CI/CD

[[LZ-3-4]]
==== LZ 3-4: Vorteile spezialisierter Linux-Distributionen für den Betrieb von Containern verstehen

Softwarearchitekt:innen verstehen, wie aktuelle Core/Container-Linux-Distributionen auf den Betrieb von Containern optimiert sind, welche Vorteile sie bieten (u. a. bzgl. Kernel- und Distributionsupdates) und welche Folgen das für die betriebenen Applikationen hat.

[[LZ-3-5]]
==== LZ 3-5: Persistenzlösungen in Cloud-Umgebungen bewerten und auswählen

Softwarearchitekt:innen kennen verschiedene Wege, um Daten zu persistieren.

Sie kennen den Unterschied von Object- und Block-Storage und können verschiedene Storage-Dienste der Cloud-Anbieter, unterschiedliche COTS-Produkte und selbstverwaltete Lösungen für unterschiedliche Einsatzszenarien klassifizieren.

Softwarearchitekt:innen verstehen die Vor- und Nachteile einer Cloud-Native-Storage-Lösung und können die höherwertigen Managed Services (wie etwa RDBMS) der Cloud-Anbieter mit der Verwendung selbstverwalteter Lösungen vergleichen.

Sie kennen verschiedene Konzepte, um Backup und Restore von persistenten Daten in der Cloud zu realisieren.
// end::DE[]

// tag::EN[]
[[LG-3-1]]
==== LG 3-1: Understand the Cloud Native Concept

Software architects understand the benefits and goals of the Cloud Native concept. They are familiar with the advantages of the concept, particularly through:

* Unified interfaces for administration and configuration
* Resource abstraction
* Delivery artifacts

References: <<davis>>

[[LG-3-2]]
==== LG 3-2: Understand Basic Container Concepts

Software architects understand the technical basics and the added value of containers and know the difference between conventional deployment and deployment with containers.

They understand how the use of containers leads to a better decoupling of responsibilities and thus to a more effective organization.

Software architects understand Linux kernel isolation mechanisms that apply to containers (container security), including:

* Namespaces and cgroups
* Capabilities

They also understand the implications, usage scenarios, and threats of privileged containers.

[[LG-3-3]]
==== LG 3-3: Understand Container Manager Abstraction Concepts

Software architects understand the abstraction concepts of current container managers and know best patterns and practices on how to apply quality requirements to them. For example:

* Finite workloads such as (cron) jobs.
* Health Check and Self Healing
* Scaling and load balancing
* Placement

References: <<davis>>, <<bruns>>, <<bilgin_huss>>

Software architects know the principles of an overlay network (VLAN) for containers and container managers and understand how different services or systems are isolated. They are familiar with requirement scenarios such as implementing a distributed firewall for isolating:

* Multiple tenants
* Test systems in the context of CI/CD

[[LG-3-4]]
==== LG 3-4: Understand the Benefits of Specialized Linux Distributions for Operating Containers

Software architects understand how current core/container Linux distributions are optimized for operating containers, the benefits they offer (including kernel and distribution updates), and the implications for the applications being run.

[[LG-3-5]]
==== LG 3-5: Evaluate and Select Persistence Solutions in Cloud Environments

Software architects are familiar with the different ways to persist data.

They understand the difference between object and block storage and can classify the different storage services provided by cloud providers, various COTS products, and self-managed solutions for different use cases.

Software architects understand the advantages and disadvantages of a cloud-native storage solution and can compare higher-level managed services (such as RDBMS) provided by cloud providers with the use of self-managed solutions.

They are familiar with various concepts for backing up and restoring persistent data in the cloud.

// end::EN[]
