=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Verschiedene Muster für die Modularisierung von Cloud-Native Architekturen kennen

Softwarearchitekt:innen kennen die Konzepte des Container Application Designs (Container Pattern), um Software-Komponenten in Container modularisieren zu können und Cloud-native Architekturen zu realisieren.

Sie kennen verschiedene Container Application Design Muster, wie zum Beispiel:

* Ambassador/Adapter/Sidekick
* Scatter & Gather
* Work Queue

Softwarearchitekt:innen kennen Methoden, um technische von fachlichen Aufgaben durch getrennte Container zu realisieren und verstehen, wie Container-Manager über dieses Prinzip technische Aufgaben übernimmt, insbesondere:

* Konfiguration und Initialisierung von Anwendungen
* Adaptive Skalierung über Custom Metrics
* Container Management durch Operator bzw. Controller

[[LZ-4-2]]
==== LZ 4-2: Passende Resilienz-Muster zur Erhöhung von Fehlertoleranz auswählen

Softwarearchitekt:innen verstehen, wie bei einer verteilten Anwendung die Kommunikation zwischen den Services fehlertolerant realisiert werden kann.

Sie verstehen, durch welche Muster Fehlertoleranz auf der Kommunikationsebene erhöht werden kann und wie gängige Service-Mesh-Konzepte verwendet werden können, um die Implementation Resilienz-Mustern vom fachlichen Code zu trennen.

Softwarearchitekt:innen kennen u. a. folgende Resilienz-Muster:

* Circuit Breaker
* Conditional Rate Limits
* Traffic Shifting

Sie kennen das Konzept von Chaos Engineering und dessen Methoden, die Systemresilienz durch gezieltes Einbringen von Störungen zu testen.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Know container application design patterns for distributed applications

Software architects know the concepts of container application design (container pattern) in order to modularize software components in containers and to realize cloud-native architectures.

They are familiar with various container application design patterns, such as:

* Ambassador/Adapter/Sidekick
* Scatter & Gather
* Work Queue

Software architects know methods to implement technical and business tasks using separate containers and understand how container managers take over technical tasks based on this principle, in particular:

* Configuration and initialization of applications
* Adaptive scaling through custom metrics
* Container management through operators or controllers

[[LG-4-2]]
==== LG 4-2: Understand resilience patterns for distributed applications

Software architects understand how communication between services can be implemented with fault tolerance in a distributed application.

They understand which patterns can increase fault tolerance at the communication level and how common service mesh concepts can be used to separate the implementation of resilience patterns from the business code.

Software architects are familiar with the following resilience patterns, among others:

* Circuit Breaker
* Conditional Rate Limits
* Traffic Shifting

They are familiar with the concept of chaos engineering and its methods to test system resilience by deliberately introducing disruptions.

// end::EN[]


