=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Projekte in oder mit der Cloud
Anforderungen an die Umsetzung von Projekten in und mit der Cloud kennen lernen, wie

* verschiedene Vorgehensweisen, um Projekte in oder mit der Cloud durchzuführen. Zum Beispiel:
** Etablierte organisatorische Methoden zur Umsetzung
** die Mean Time To Recovery (MTTR) zur Verbesserung der Verfügbarkeit der Anwendung
** Gestaltung von Development- und CI/CD-Umgebungen
* Möglichkeiten, um in einer Cloud-Umgebung Deployments und ein Application Lifecycle Management zu realisieren, insbesondere:
** Versionierung von Containern und Deployment-Spezifikationen u. a.
** Etablierte Formen der Bereitstellung von Anwendungen, wie z. B.:
*** Rolling Deployment
*** Canary Deployment
*** Blue/Green Deployment
* Komponenten und Vorgehensmodelle, um einen schnellen Test- und Deployment-Prozess zu realisieren. Insbesondere Konzepte zum Dev-, Test-, Staging-, Prod-Cluster Design wie:
** Gestaltung der Cluster in den Bereitstellungsstufen
** Verantwortlichkeiten und Zugriffskontrolle
** Etablierte Methoden zur Komponentengruppierung

[[LZ-5-2]]
==== LZ 5-2: Beobachtbarkeit
Anforderungen an die Beobachtbarkeit und das Monitoring kennen lernen, wie

* die besonderen Rahmenbedingungen verteilter Anwendungen und deren Einfluss auf die Beobachtbarkeit mittels:
** Logging
** Monitoring
** Metriken
** Alerting
** Distributed Tracing
* Wege und Verantwortlichkeiten zur Erstellung möglichst fehlervorhersagenden Time Series Queries für Alerts
// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Projects in or with the cloud
Know the requirements for the implementation of projects in and with the cloud, like

* verschiedene Vorgehensweisen, um Projekte in oder mit der Cloud durchzuführen. Zum Beispiel:
** Etablierte organisatorische Methoden zur Umsetzung
** die Mean Time To Recovery (MTTR) zur Verbesserung der Verfügbarkeit der Anwendung
** Gestaltung von Development- und CI/CD-Umgebungen
* Möglichkeiten, um in einer Cloud-Umgebung Deployments und ein Application Lifecycle Management zu realisieren, insbesondere:
** Versionierung von Containern und Deployment-Spezifikationen u. a.
** Etablierte Formen der Bereitstellung von Anwendungen, wie z. B.:
*** Rolling Deployment
*** Canary Deployment
*** Blue/Green Deployment
* Komponenten und Vorgehensmodelle, um einen schnellen Test- und Deployment-Prozess zu realisieren. Insbesondere Konzepte zum Dev-, Test-, Staging-, Prod-Cluster Design wie:
** Gestaltung der Cluster in den Bereitstellungsstufen
** Verantwortlichkeiten und Zugriffskontrolle
** Etablierte Methoden zur Komponentengruppierung

* Know different approaches to execute projects in or with the cloud. For example:
** Organizational best practices
** Development and CI/CD environments
* Know ways to implement deployments and application lifecycle management in a cloud environment with container managers, specifically:
** Container versioning and deployment specifications, etc.
** Canary Releases and Blue Green Deployment
* get to know components and procedure models to realize a fast test and deployment process. In particular, concepts related to the Dev/Test/Prod cluster such as:
** responsibilities and access control
** Best practices for component clustering
** Tests and testability

[[LG-5-2]]
==== LG 5-2: Observability
Know the requirements for observability and monitoring, like

* die besonderen Rahmenbedingungen verteilter Anwendungen und deren Einfluss auf die Beobachtbarkeit mittels:
** Logging
** Monitoring
** Metriken
** Alerting
** Distributed Tracing
* Wege und Verantwortlichkeiten zur Erstellung möglichst fehlervorhersagenden Time Series Queries für Alerts

* learn how to ensure observability, which is essential for a distributed application
** logging
** Monitoring/metrics and alerting
** Distributed Tracing
* learn ways and responsibilities to create time series queries for alerts that are as predictive of errors as possible.

// end::EN[]


