// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Praktische Erfahrung in Entwurf und Entwicklung kleiner bis mittelgroßer Softwaresysteme
- Erste praktische Erfahrung in Wartung oder Weiterentwicklung von Softwaresystemen
- Erste praktische Erfahrung im Umgang mit Containern und deren Deployment

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Kenntnisse oder erste praktische Erfahrung in der Herleitung und Inbetriebnahme moderner Microservice-Architekturen
- Erste praktische Erfahrung im Umgang mit Container-Managern
- Erste praktische Erfahrung mit gängigen Cloud-Anbietern

// end::DE[]

// tag::EN[]
=== Prerequisites

Participants **should** have the following prerequisite knowledge:

- Practical experience in design and development of small to medium sized software systems
- First practical experience in maintenance or further development of software systems
- First practical experience in working with containers and their deployment

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Knowledge or first practical experience in deriving and deploying modern microservice architectures
- First practical experience in dealing with container managers
- First practical experience with common cloud providers
// end::EN[]
