// header file for curriculum section "References"
// (c) iSAQB e.V. (https://isaqb.org)
// ===============================================

[bibliography]
== {references}

// tag::DE[]
Dieser Abschnitt enthält Ressourcen, die zur Erfüllung des Lehrplans verwendet werden sollten.
// end::DE[]

// tag::EN[]
This section contains resources that should be used to fulfill the curriculum.
// end::EN[]

- Brendan Burns: Designing Distributed Systems. Patterns and Paradigms for Scaleable, Reliable Services. O'Reilly Media, 2018

- Cornelia Davis: Cloud Native Patterns. Designing Change-tolerant Software. Manning, 2019

- Ibryam Bilgin, Roland Huss: Kubernetes Patterns. Reusable Elements for Designing Cloud Native Applications. O'Reilly Media, Second edition, 2023

- Beyer Betsy, Chris Jones, Jennifer Petoff, Niall Richard Murphy: Site Reliability Engineering. How Google Runs Production Systems. O'Reilly, 2016

- Gene Kim, Jez Humble, Patrick Debois, John Willis, John Allspaw: The Devops Handbook. How to Create World-Class Agility Reliability and Security in Technology Organizations. IT Revolution Press, Second edition, 2021

