// tag::DE[]
|===
| Dauer: 120 Min. | Übungszeit: 0 Min.
|===

=== Begriffe und Konzepte

Cloud, *aaS, Cloud-Ausprägungen, Vendor Lock-in, Service-Level Agreement (SLA), Infrastructure as Code, Umsetzung moderner Microservice-Architekturen, verteilte Anwendungen, Container, Container-Manager, Cloud-Anbieter, On Premise, Manages Services, Cloud-Native Services, Rechtliche Anforderungen an Cloud-Betrieb, Cloud- Muster, Cloud-Migrationsmuster, Organisation Cloud-Übergang, Bare Metal, Time-to-Market, Verfügbarkeit, Skalierung, Performance, IOPS, Decoupling Operations, Networking, Applikations-Orientierung.

// end::DE[]

// tag::EN[]
|===
| Duration: 120 min | Practice time: 0 min
|===

=== Terms and Principles

IaaS, SaaS, PaaS, CaaS, FaaS etc. Infrastructure as Code, implementation of modern microservice architectures, distributed applications, containers, container managers, cloud providers, bare metal, time-to-market, availability, scaling, performance, IOPS, decoupling operations, private/public cloud, networking, application orientation.
// end::EN[]





