=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Im Cloud Umfeld verwendete Begriffe verstehen und unterscheiden

Softwarearchitekt:innen kennen die im Cloud Umfeld verwendeten Begriffe und können deren Bedeutung unterscheiden.

Sie verstehen die Definition des Begriffs Cloud und kennen unterschiedliche Cloud-Arten (Public, Private, On-Premise, Hybrid/Multi).

Sie kennen die Unterschiede zwischen Cloud-Anbieter und On Premise Betrieb. Außerdem kennen sie die Gründe für den Betrieb in der Cloud und die Vor- und Nachteile dieser Betriebsform.

Sie verstehen, wie der reduzierte Umfang von notwendigen Hosting-Kompetenzen bei der Verwendung eines Cloud-Anbieters sich auf Risiko und Kosten auswirkt.

Sie verstehen welche Cloud-Art für welchen Einsatz am besten geeignet ist und wann dennoch der Einsatz von eigener Hardware (Bare Metal) sinnvoller sein kann.

Teilnehmende kennen unterschiedliche Cloud Service Modelle (*aaS) und können Services anhand dieser Modelle klassifizieren.

Sie kennen den Begriff Vendor Lock-in und dessen Zusammenhang mit Managed Services sowie Cloud Native Services.

Sie verstehen den Unterschied zwischen Cloud-Muster und Cloud-Migrationsmuster.

Sie kennen die organisatorischen Aspekte der Cloud Migration und die rechtlichen Rahmenbedingungen für einen Betrieb von Anwendungen in der Cloud. 

Sie verstehen, dass sowohl die Aspekte der Datensicherheit für die Entscheidung für oder gegen eine Public Cloud relevant sind und dass organisatorische und/oder rechtliche Anforderungen die Wahl der verwendeten Cloud-Art beeinflussen.

Teilnehmende kennen die Auswirkungen der Cloud auf Time-to-Market, Verfügbarkeit, Skalierung, Performance, IOPS, Decoupling Operations und Networking hat.

Sie verstehen, dass Cloud Anwendungen und deren Anforderungen an die Verfügbarkeit, die Skalierung und Performance die Verteilung auf mehrere Verfügbarkeitszonen und Rechenzentren verlangen.

Sie verstehen, welche Anforderungen die Performance an die Infrastruktur und die maximal möglichen IOPS stellt.
// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Terms and Cloud Provider
Understand, differentiate and classify terms used in the cloud environment, such as

* Definition des Begriffs Cloud
* unterschiedliche Cloud-Arten (Public, Private, On-Premise, Hybrid/Multi)
* die Unterschiede zwischen Cloud-Anbieter und On Premise
* die Gründe für den Betrieb in der Cloud und deren Vor- und Nachteile
* wie der reduzierte Umfang von notwendigen Hosting-Kompetenzen bei der Verwendung eines Cloud-Anbieters Risiko und Kosten reduziert
* welche Cloud-Art für welchen Einsatz am besten geeignet ist und wann dennoch der Einsatz von eigener Hardware (Bare Metal) sinnvoller sein kann
* unterschiedliche Cloud Service Modelle (*aaS)
* den Begriff Vendor Lock-in und dessen Zusammenhang mit Managed Services sowie Cloud Native Services
* den Unterschied zwischen Cloud-Muster und Cloud-Migrationsmuster
* die organisatorischen Aspekte der Cloud Migration
* die rechtlichen Rahmenbedingungen für einen Betrieb von Anwendungen in der Cloud
* dass sowohl die Aspekte der Datensicherheit für die Entscheidung für oder gegen eine Public Cloud relevant sind
* dass organisatorische und/oder rechtliche Anforderungen die Wahl der verwendeten Cloud-Art beeinflussen
* welche Auswirkungen die Cloud auf Time-to-Market, Verfügbarkeit, Skalierung, Performance, IOPS, Decoupling Operations und Networking hat
* dass Cloud Anwendungen und deren Anforderungen an die Verfügbarkeit, die Skalierung und Performance die Verteilung auf mehrere Verfügbarkeitszonen und Rechenzentren verlangen
* welche Anforderungen die Performance an die Infrastruktur und die maximal möglichen IOPS stellt
* Know how to distinguish the different *aaS terms, public/private cloud and can classify existing offerings
* know and understand the reasons for operating in the cloud and can assess the advantages and disadvantages
* understand how and to what extent VMs and networks can be set up and configured with common cloud providers
* Understand that the high level of automation possible in provisioning/scaling and the availability of higher-value services are key reasons for using a cloud provider
* Know which type of provider is best suited for which deployment, and yet when it may make more sense to use in-house hardware (bare metal)
* learn that data security aspects are relevant for the decision for or against a public cloud, as well as the performance of the VMs and the maximum possible IOPS
* learn that modern architectures and their availability requirements demand that the application be distributed across multiple machines and data centers
* learn how the reduced scope of hosting skills required when using a cloud provider reduces risk and cost
// end::EN[]


