=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Cloud-Arten verstehen und unterscheiden

Softwarearchitekt:innen kennen die gängigen Cloud-Begriffe und können verschiedene Arten wie Public, Private, Hybrid/Multi und On-Premise voneinander unterscheiden. 

Sie verstehen, dass der Hybrid/Multi Cloud Betrieb keine Ausnahme darstellt und können die Gründe von Hybrid/Multi Cloud Betrieb benennen, beispielsweise:

* Schrittweise Migration in die Cloud
* Kostenersparnis beim Betrieb
* Datenschutz und Datensicherheit
* Integration mit Bestandssystemen

Sie verstehen den Unterschied zwischen Public Cloud- und On-Premise-Betrieb sowie die Herausforderungen und Argumente für und gegen den Public Cloud-Betrieb. Sie erkennen auch, wann der Einsatz von eigener Hardware (Bare Metal) sinnvoller ist.

[[LZ-1-2]]
==== LZ 1-2: Entscheidungskriterien für die Nutzung von managed Services und self-managed Services verstehen

Softwarearchitekt:innen kennen unterschiedliche Cloud Service Modelle (*aaS) und können Services anhand dieser Modelle klassifizieren.

Sie verstehen darüber hinaus das Serverless Computing Konzept und können es den Cloud Service Modellen zuordnen.

Softwarearchitekt:innen verstehen das Shared-Responsibility-Modell und dessen Relevanz für Kosten- und Risikobewertungen bei der Nutzung von managed Cloud Services.

Sie kennen das Konzept des Vendor Lock-in und seine Relevanz für die Entscheidungsfindung zwischen managed und self-managed Services.

[[LZ-1-3]]
==== LZ 1-3: Compliance und organisatorische Aspekte bei der Cloud-Architektur berücksichtigen

Softwarearchitekt:innen kennen die organisatorischen Aspekte der Cloud Migration und die rechtlichen Rahmenbedingungen für einen Betrieb von Anwendungen in der Cloud, z. b.:

* DSGVO (GDPR)
* BSI C5 (Kriterienkatalog Cloud Computing)
* ISO 27001
* BSI IT-Grundschutz

Sie verstehen, dass die Aspekte der Datensicherheit für die Entscheidung für oder gegen eine Public Cloud relevant sind und dass organisatorische und/oder rechtliche Anforderungen die Wahl der verwendeten Cloud-Art beeinflussen.

[[LZ-1-4]]
==== LZ 1-4: Verfügbarkeit, Skalierung und Performance als Anforderungsparameter beim Cloud-Architektur-Design anwenden

Softwarearchitekt:innen kennen die Auswirkungen der Cloud auf Time-to-Market, Verfügbarkeit, Skalierung, Performance, IOPS, Decoupling Operations und Networking.

Sie können einschätzen, wann Cloud-Anwendungen eine Verteilung über mehrere Verfügbarkeitszonen und Rechenzentren erfordern.

Sie kennen die Leistungsanforderungen an die Infrastruktur und die Limitierungen der Public Cloud, wie z.B. IOPS für Speicher.
// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Understand and Differentiate Cloud Types

Software architects know the common cloud terms and can distinguish between different types such as public, private, hybrid/multi and on-premise.

They understand that hybrid/multi-cloud operation is no exception and can name the reasons for hybrid/multi-cloud operation, for example:

* Gradual migration to the cloud
* Cost savings during operation
* Data protection and data security
* Integration with existing systems

Software architects understand the difference between public cloud and on-premise operation as well as the challenges and arguments for and against public cloud operation. They also recognize when it makes more sense to use dedicated hardware (bare metal).

[[LG-1-2]]
==== LG 1-2: Understand Decision Criteria for the Use of Managed Services and Self-Managed Services

Software architects know different cloud service models (*aaS) and can classify services based on these models.

They also understand the serverless computing concept and can assign it to the cloud service models.

Software architects understand the shared responsibility model and its relevance for cost and risk assessments when using managed cloud services.

They know the concept of vendor lock-in and its relevance for decision-making between managed and self-managed services.

[[LG-1-3]]
==== LG 1-3: Incorporate Compliance and Organizational Aspects Into Cloud Architecture

Software architects are familiar with the organizational aspects of cloud migration and the legal framework for operating applications in the cloud, e.g:

* DSGVO (GDPR)
* BSI C5 (Cloud Computing Compliance Criteria Catalogue)
* ISO 27001
* BSI IT-Grundschutz (A systematic basis for information security)

They understand that the aspects of data security are relevant for the decision for or against a public cloud and that organizational and/or legal requirements influence the choice of the type of cloud used.

[[LG-1-4]]
==== LG 1-4: Apply Availability, Scaling and Performance Requirements as Parameters in Cloud Architecture Design

Software architects understand the impact of the cloud on time-to-market, availability, scaling, performance, IOPS, decoupling operations, and networking.

They can assess when cloud applications require distribution across multiple availability zones and data centers.

Know infrastructure performance requirements and public cloud limitations, such as IOPS for storage.
// end::EN[]


