=== {learning-goals}

// tag::DE[]
[[LZ-1-1]]
==== LZ 1-1: Begriffe und Cloud Anbieter
* kennen die Definition der Cloud
* wissen die unterschiedlichen Cloud Service Modelle (*aaS), Cloud-Arten (Public, Private, On-Premise, Hybrid/Multi) zu unterscheiden und können bestehende Angebote klassifizieren
* kennen und verstehen die Gründe für den Betrieb in der Cloud und können die Vor- und Nachteile einschätzen
* verstehen, wie und in welchem Umfang bei gängigen Cloud-Anbietern VMs und Netzwerke eingerichtet und konfiguriert werden können
* verstehen, dass der hohe mögliche Grad von Automatisierung bei der Provisionierung/Skalierung und die Verfügbarkeit von höherwertigen Diensten Hauptgründe für die Verwendung eines Cloud-Anbieters sind
* wissen, welcher Typ von Anbieter für welchen Einsatz am besten geeignet ist und wann dennoch der Einsatz von eigener Hardware (Bare Metal) sinnvoller sein kann
* lernen, dass sowohl die Aspekte der Datensicherheit für die Entscheidung für oder gegen eine Public Cloud relevant sind, wie auch die Performanz der VMs und die maximal möglichen IOPS
* lernen, dass Moderne Architekturen und deren Anforderungen an die Verfügbarkeit die Verteilung der Applikation auf mehrere Maschinen und Rechenzentren verlangen
* lernen, wie der reduzierte Umfang von notwendigen Hosting-Kompetenzen bei der Verwendung eines Cloud-Anbieters Risiko und Kosten reduziert
* verstehen, dass organisatorische und/oder rechtliche Anforderungen die Wahl der verwendeten Cloud-Arten beeinflussen sollten.
// end::DE[]

// tag::EN[]
[[LG-1-1]]
==== LG 1-1: Terms and Cloud Provider
* Know how to distinguish the different *aaS terms, public/private cloud and can classify existing offerings
* know and understand the reasons for operating in the cloud and can assess the advantages and disadvantages
* understand how and to what extent VMs and networks can be set up and configured with common cloud providers
* Understand that the high level of automation possible in provisioning/scaling and the availability of higher-value services are key reasons for using a cloud provider
* Know which type of provider is best suited for which deployment, and yet when it may make more sense to use in-house hardware (bare metal)
* learn that data security aspects are relevant for the decision for or against a public cloud, as well as the performance of the VMs and the maximum possible IOPS
* learn that modern architectures and their availability requirements demand that the application be distributed across multiple machines and data centers
* learn how the reduced scope of hosting skills required when using a cloud provider reduces risk and cost
// end::EN[]


