=== {learning-goals}


// tag::DE[]
[[LZ-5-1]]
==== LZ 5-1: Infrastructure as Code
* lernen die Möglichkeiten der Automatisierung zum vorhersehbaren Erzeugen, Verändern und Verbessern der Infrastruktur kennen und zu unterscheiden, u. a.:
** Ansible
** Chef
** Terraform
* kennen Best Practices, um unterschiedliche Konfigurationen der Infrastruktur verwalten
* lernen die API unterschiedlicher Cloud-Anbieter kennen und einzusetzen

[[LZ-5-2]]
==== LZ 5-2: Container-Management-Plattformen
lernen vollständige Container-Management-Plattformen und Tools zur Administration kennen, wie zum Beispiel:

* Rancher
* Tectonic, Kops oder Kubeadm
* OpenShift

// end::DE[]

// tag::EN[]
[[LG-5-1]]
==== LG 5-1: Infrastructure as Code
* Learn about and distinguish between automation options for predictably creating, modifying, and improving infrastructure, including:
** Ansible
** Chef
** Terraform
* Know best practices to manage different configurations of infrastructure
* learn about and use the API of different cloud providers

[[LG-5-2]]
==== LG 5-2: Container Management Platforms
learn complete container management platforms and tools for administration, such as:

* Rancher
* Tectonic, Kops or Kubeadm
* OpenShift
// end::EN[]


