=== {learning-goals}


// tag::DE[]
[[LZ-6-1]]
==== LZ 6-1: DevOps, DevSecOps
* lernen die Definition von DevOps und DevSecOps kennen und zu unterscheiden
* kennen die Herausforderungen vom Übergang klassischer Strukturen zu DevOps bzw. DevSecOps kennen

[[LZ-6-2]]
==== LZ 6-2: Site Reliability Engineering
* lernen die Definition von Site Reliability Engineering kennen
* lernen Herausforderungen des Site Reliability Engineering kennen
* lernen Methoden zum Site Reliability Engineering kennen

[[LZ-6-3]]
==== LZ 6-3: Infrastructure as Code
* lernen die Möglichkeiten der Automatisierung zum vorhersehbaren Erzeugen, Verändern und Verbessern der Infrastruktur kennen und zu unterscheiden:
** lernen Werkzeuge zur automatisierten Bereitstellung von Cloud Infrastruktur kennen und zu unterscheiden
** lernen die API unterschiedlicher Cloud-Anbieter kennen und einzusetzen 
* kennen etablierte Vorgehensweisen, um unterschiedliche Konfigurationen der Infrastruktur verwalten
* kennen Unterschied zwischen Konfiguration und Provisionierung

[[LZ-6-4]]
==== LZ 6-4: Abstraktionsebenen von Container-Managern
* kennen weitere Abstraktionsebenen von Container-Managern und können sie unterscheiden.
* kennen die Einsatzmöglichkeiten vom Container-Managern und ihren Werkzeugen

[[LZ-6-5]]
==== LZ 6-5: Berechnungen
können u. a. folgende Berechnungen überschlägig durchführen:

* Verfügbarkeit
* Größe eines Clusters

// end::DE[]

// tag::EN[]
[[LG-6-1]]
==== LG 6-1: Infrastructure as Code
* Learn about and distinguish between automation options for predictably creating, modifying, and improving infrastructure, including:
** Ansible
** Chef
** Terraform
* Know best practices to manage different configurations of infrastructure
* learn about and use the API of different cloud providers

[[LG-6-2]]
==== LG 6-2: Container Management Platforms
learn complete container management platforms and tools for administration, such as:

* Rancher
* Tectonic, Kops or Kubeadm
* OpenShift

[[LZ-6-5]]
==== LZ 6-5: Berechnungen
können u. a. folgende Berechnungen überschlägig durchführen:
// end::EN[]


